package publisher

import (
	"os"
	"strings"
	"testing"
)

func TestBuildReviewBody_WithDisclosure(t *testing.T) {
	disclosure := "This review was generated by AI."
	review := "Looks good overall, minor nit on line 42."
	author := "octocat"

	body := BuildReviewBody(review, true, disclosure, author)

	if !strings.Contains(body, disclosure) {
		t.Errorf("expected body to contain disclosure text %q", disclosure)
	}
	if !strings.Contains(body, review) {
		t.Errorf("expected body to contain review content %q", review)
	}
	if !strings.Contains(body, "cc @octocat") {
		t.Error("expected body to contain cc @octocat")
	}
	// Disclosure should come before the review content.
	discIdx := strings.Index(body, disclosure)
	revIdx := strings.Index(body, review)
	if discIdx >= revIdx {
		t.Error("expected disclosure text to appear before review content")
	}
}

func TestBuildReviewBody_WithoutDisclosure(t *testing.T) {
	disclosure := "This review was generated by AI."
	review := "LGTM!"
	author := "octocat"

	body := BuildReviewBody(review, false, disclosure, author)

	if strings.Contains(body, disclosure) {
		t.Error("expected body NOT to contain disclosure text when disabled")
	}
	if !strings.Contains(body, review) {
		t.Errorf("expected body to contain review content %q", review)
	}
	if !strings.Contains(body, "cc @octocat") {
		t.Error("expected body to contain cc @octocat")
	}
}

func TestSaveDryRunReview(t *testing.T) {
	dir := t.TempDir()

	params := SaveParams{
		ReviewsDir: dir + "/reviews",
		Repo:       "owner/repo",
		PRNumber:   42,
		PRTitle:    "Add widget feature",
		PRAuthor:   "octocat",
		Body:       "This PR looks great.",
	}

	path, err := SaveDryRunReview(params)
	if err != nil {
		t.Fatalf("SaveDryRunReview returned error: %v", err)
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Fatalf("expected file to exist at %s", path)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read review file: %v", err)
	}

	content := string(data)

	if !strings.Contains(content, "Add widget feature") {
		t.Error("expected file to contain PR title")
	}
	if !strings.Contains(content, "This PR looks great.") {
		t.Error("expected file to contain review body")
	}
	if !strings.Contains(content, "owner/repo#42") {
		t.Error("expected file to contain repo#number")
	}
	if !strings.Contains(content, "dry-run") {
		t.Error("expected file to contain mode dry-run")
	}
}

func TestReviewFilePath(t *testing.T) {
	path := reviewFilePath("/tmp/reviews", "owner/repo", 42)

	expected := "/tmp/reviews/owner-repo-42.md"
	if path != expected {
		t.Errorf("expected %q, got %q", expected, path)
	}
}
